# -*- coding: utf-8 -*-
"""cursos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPfyu0YcoqftJt_itpYBCFub4eSehIvK
"""

import pandas as pd

url = "https://raw.githubusercontent.com/axelmartinezportillo/elt-data-pipelin2523182022/refs/heads/main/data/raw/A_cursos.csv"
df = pd.read_csv(url)
df.head()

#exploracion de datos
df.shape
df.info()
df.isnull().sum()

#Limpieza
cursos = df.copy()
cursos.columns = cursos.columns.str.strip().str.lower()

for col in cursos.select_dtypes(include='object').columns:
    cursos[col] = cursos[col].astype(str).str.strip()

# Limpiar columna créditos
cursos['creditos'] = cursos['creditos'].str.replace(' cr', '', case=False)
cursos['creditos'] = pd.to_numeric(cursos['creditos'], errors='coerce')

cursos = cursos.replace(['nan', 'None', ''], pd.NA)
cursos = cursos.replace(r'^\s*$', pd.NA, regex=True)
cursos = cursos.drop_duplicates()
print("Paso 9: Limpieza de cursos completada.")

#seapara datos validos y rechazados
validos = cursos[cursos['id_curso'].notna() &
          cursos['curso'].notna()].copy()
rechazados = cursos[cursos['id_curso'].isna() |
              cursos['curso'].isna()].copy()
print(f"Paso 10: Separación de cursos finalizada. Válidos: {len(validos)}, Rechazados: {len(rechazados)}")

#motivo de rechazo
def motivo_cur(row):
    motivos = []
    if pd.isna(row['id_curso']): motivos.append("id_curso_vacio")
    if pd.isna(row['curso']): motivos.append("nombre_curso_vacio")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo_cur, axis=1)

#exportar archivos
validos.to_csv("cursos_curated.csv", index=False)
rechazados.to_csv("cursos_rejects.csv", index=False)
print(" Archivos de cursos exportados.")

#CONECTAR RENDER
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:6r5AQWoE44HrllVAUznGZiLVeK6jjHfX@dpg-d6qu5ochg0os73b4g0v0-a.oregon-postgres.render.com/etl_seguros_fv1v"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

#cargar datos en postegre
validos.to_sql('cursos_curated',
      engine,
      if_exists='append',
               index=False)
rechazados.to_sql('cursos_rejects',
            engine,
              if_exists='append',
                  index=False)
print("Paso 14: Carga de cursos a Render completada.")

#validar carga
pd.read_sql(
    "SELECT * FROM cursos_curated",
    engine)