# -*- coding: utf-8 -*-
"""estudiantes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDzgu-sSI4AyR49Fx83VRdrJlx3kTCaQ
"""

import pandas as pd

url = "https://raw.githubusercontent.com/axelmartinezportillo/elt-data-pipelin2523182022/refs/heads/main/data/raw/A_estudiantes.csv"
df = pd.read_csv(url)
df.head()

#exploracion de datos
df.shape
df.columns
df.info()
df.isnull().sum()

#limpieza de datos
estudiantes = df.copy()
estudiantes.columns = estudiantes.columns.str.strip().str.lower()

for col in estudiantes.select_dtypes(include='object').columns:
    estudiantes[col] = estudiantes[col].astype(str).str.strip()

estudiantes = estudiantes.replace(['nan', 'None', ''], pd.NA)
estudiantes = estudiantes.replace(r'^\s*$', pd.NA, regex=True)

# Limpieza de formato de edad y correo
estudiantes['edad'] = estudiantes['edad'].str.replace(' años', '', case=False)
estudiantes['edad'] = pd.to_numeric(estudiantes['edad'], errors='coerce')
estudiantes['correo'] = estudiantes['correo'].str.lower()

estudiantes = estudiantes.drop_duplicates()

#separar datos validos y rechazados
columnas_clave = ['id_estudiante', 'nombre', 'correo']

validos = estudiantes[
    estudiantes[columnas_clave].notna().all(axis=1)
].copy()

rechazados = estudiantes[
    estudiantes[columnas_clave].isna().any(axis=1)
].copy()
print(f"Paso 10: Separación finalizada. Válidos: {len(validos)}, Rechazados: {len(rechazados)}")

#motivo de rechazo
def motivo_estudiantes(row):
    motivos = []
    if pd.isna(row['id_estudiante']):
        motivos.append("id_estudiante_vacio")
    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")
    if pd.isna(row['correo']) or "@" not in str(row['correo']):
        motivos.append("correo_invalido_o_vacio")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo_estudiantes, axis=1)

#Exportar Archivos
validos.to_csv("estudiantes_curated.csv", index=False)
rechazados.to_csv("estudiantes_rejects.csv", index=False)

#CONECTAR RENDER
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:6r5AQWoE44HrllVAUznGZiLVeK6jjHfX@dpg-d6qu5ochg0os73b4g0v0-a.oregon-postgres.render.com/etl_seguros_fv1v"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

#cargar datos en PostreSQl
validos.to_sql('estudiantes_curated', engine, if_exists='append', index=False)
rechazados.to_sql('estudiantes_rejects', engine, if_exists='append', index=False)

#validar la carga
pd.read_sql(
    "SELECT * FROM estudiantes_curated",
    engine)