# -*- coding: utf-8 -*-
"""Notas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1af7_a822lnF10Zop1h8bmYfLESilRQFG
"""

import pandas as pd

url = "https://raw.githubusercontent.com/axelmartinezportillo/elt-data-pipelin2523182022/refs/heads/main/data/raw/A_notas.csv"
df = pd.read_csv(url)
df.head()

#explorar archivos
df.shape
df.info()
df.isnull().sum()
print("Exploración de notas completada.")

#limpieza datos
notas = df.copy()
notas.columns = notas.columns.str.strip().str.lower()

# Convertir nota a número (esto vuelve NaN a la palabra "diez" y a los vacíos)
notas['nota'] = pd.to_numeric(notas['nota'], errors='coerce')

for col in notas.select_dtypes(include='object').columns:
    notas[col] = notas[col].astype(str).str.strip()

notas = notas.replace(['nan', 'None', ''], pd.NA)
notas = notas.replace(r'^\s*$', pd.NA, regex=True)
notas = notas.drop_duplicates()
print(" Limpieza de notas completada.")

#separar datos validos y rechazados
columnas_obligatorias = ['id_estudiante', 'id_curso', 'nota']

validos = notas[notas[columnas_obligatorias].notna().all(axis=1)].copy()
rechazados = notas[notas[columnas_obligatorias].isna().any(axis=1)].copy()
print(f" Separación de notas finalizada. Válidos: {len(validos)}, Rechazados: {len(rechazados)}")

#motivo rechazo
def motivo_not(row):
    motivos = []
    if pd.isna(row['id_estudiante']): motivos.append("id_estudiante_vacio")
    if pd.isna(row['id_curso']): motivos.append("id_curso_vacio")
    if pd.isna(row['nota']): motivos.append("nota_invalida_o_vacia")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo_not, axis=1)

#exportar archivos
validos.to_csv("notas_curated.csv", index=False)
rechazados.to_csv("notas_rejects.csv", index=False)
print(" Archivos de notas exportados.")

#CONECTAR RENDER
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:6r5AQWoE44HrllVAUznGZiLVeK6jjHfX@dpg-d6qu5ochg0os73b4g0v0-a.oregon-postgres.render.com/etl_seguros_fv1v"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

#cargar datos en postgresql
validos.to_sql('notas_curated', engine, if_exists='append', index=False)
rechazados.to_sql('notas_rejects', engine, if_exists='append', index=False)
print(" Carga de notas a Render completada.")

#validar carga
pd.read_sql("SELECT * FROM notas_curated", engine)